kind = "api"
previewPath = "/api"
title = "API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 5000
name = "API Server"
paths = ["/api"]

[services.development]
run = "echo 'API Server not used in this project'"

[services.production]

[services.production.run]
args = ["echo", "API Server not used"]

[services.production.run.env]
PORT = "5000"
